name: example
description: An example for showcasing playx theme widget.
version: 0.0.2
publish_to: none

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  playx_theme:
    path: ../

dependency_overrides: 
  win32: ^5.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
