name: playx_theme
description: Easily change and configure current app theme with a lot of features like having custom colors for each theme and more.
version: 0.2.0
homepage: https://github.com/playx-flutter/playx_theme
repository: https://github.com/playx-flutter/playx_theme
issue_tracker: https://github.com/playx-flutter/playx_theme/issues
topics:
  - theme
  - colorscheme
  - material3
  - playx

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  playx_core: ^0.1.2
  flex_seed_scheme: ^1.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
