name: playx_theme
description: Easily change and configure current app theme with a unique animation and more.
version: 0.4.3
homepage: https://github.com/playx-flutter/playx_theme
repository: https://github.com/playx-flutter/playx_theme
issue_tracker: https://github.com/playx-flutter/playx_theme/issues
topics:
  - playx
  - theme
  - colorscheme
  - material3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  playx_core: ^0.4.1
  flex_seed_scheme: ^1.4.0
  animated_theme_switcher: ^2.0.10



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
