name: test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.3

      - name: Install deps
        run: flutter packages get

      - name: Format
        run: flutter format --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze lib test example

      - name: Test
        run: flutter test --coverage

      - name: Check Test Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
        with:
          min_coverage: 91
